import { db } from '#/common/libs/firebase.lib'
import { logger } from '#/common/libs/logger.lib'
import { AIService } from '#/common/services/ai.service'
import { sseBroker } from '#/common/services/sse-broker.service'
import { getLocalTime } from '#/common/utils/datetime.util'
import { ScheduleRepository } from '#/features/schedules/v1/schedule.repository'
import { ScheduleService } from '#/features/schedules/v1/schedule.service'
import { TodoRepository } from '#/features/todos/v1/todo.repository'
import { TodoService } from '#/features/todos/v1/todo.service'
import { acquireRunLock } from '#/worker/schedule/schedule-lock'

import type { ILlmUsageMeta } from '#/common/services/usage-logger.service'
import type { TChatSseEvent } from '#/features/chats/v1/chat.type'
import type { IScheduleModule } from '#/worker/schedule/schedule.type'

type TToastQuickReply = NonNullable<Extract<TChatSseEvent, { type: 'toast' }>['quick_reply']>
type TToastQuickReplyItem = TToastQuickReply[number]

interface IBriefing {
  text: string
  quickReply: TToastQuickReply
}

const BRIEFING_INSTRUCTION = `คุณคือผู้ช่วยส่วนตัวที่สรุปภารกิจวันนี้ให้ผู้ใช้เป็นภาษาไทย แบบกระชับ ตรงประเด็น
เขียนสไตล์ "บอกสิ่งที่มีวันนี้ตามตัวเลข" จบในประโยคเดียว

ตัวอย่างโทน (ภาษาอังกฤษ เพื่อให้เห็นสไตล์ ไม่ใช่ให้แปลตรงตัว):
"You have 3 meetings, 5 unread from work, and Sara wants to grab coffee tomorrow."

ให้เขียนเวอร์ชันภาษาไทยในสไตล์เดียวกัน เช่น:
"วันนี้คุณมี 3 นัดหมาย และ 5 สิ่งที่ต้องทำ"

ข้อกำหนดเด็ดขาด:
- ใช้ตัวเลขตามที่กำหนดให้เท่านั้น ห้ามเปลี่ยน ห้ามเพิ่ม ห้ามมั่วจำนวนหรือหมวดที่ไม่ได้ระบุ (เช่น ห้ามแต่ง "อีเมล" หรือ "เพื่อนชวน" ขึ้นมาเองถ้าไม่ได้ให้มา)
- กระชับ ไม่เกิน ~120 ตัวอักษร ขึ้นต้นด้วยสิ่งที่มีวันนี้ได้เลย ไม่ต้องเกริ่นทักทายยาว
- เขียนแค่ประโยคสรุป "ห้ามใส่คำชวนกด/แตะ เช่น 'แตะเพื่อวางแผน' เอง" (ระบบจะเติมให้ทีหลัง)
- ตอบกลับเป็น "ข้อความล้วน" บรรทัดเดียว ห้ามใส่เครื่องหมายคำพูด ห้ามขึ้นบรรทัดใหม่ ห้ามใส่ JSON
- ห้ามใส่ emoji เด็ดขาด`

/** Always-appended call-to-action (kept out of the LLM so it never goes missing). */
const PLAN_CTA = 'แตะเพื่อวางแผนวันของคุณ'

/** A "message" quick reply: tapping it sends `text` to the agent as a user message. */
function messageQuickReply(label: string, text: string): TToastQuickReplyItem {
  return { type: 'action', action: { type: 'message', label, text } }
}

/**
 * Daily cron: at 08:00 send each user a short "morning briefing" as a transient
 * TOAST (SSE only — NOT persisted to chat history) summarizing what's on their plate
 * today (appointments + pending todos). The wording is generated by an LLM for a natural
 * feel, with a deterministic template fallback. Token usage is recorded in the central
 * `llm_usage_log` ledger (by AIService.generate) for internal cost evaluation — this is a
 * free service: users are NOT charged credits and nothing is written to their chat history.
 */
export class SendDailyBriefingModule implements IScheduleModule {
  readonly name = 'send-daily-briefing'
  readonly cronPattern = '0 8 * * *' // 08:00 daily
  readonly timezone = 'Asia/Bangkok'

  private readonly scheduleService = new ScheduleService(new ScheduleRepository())
  private readonly todoService = new TodoService(new TodoRepository())
  private readonly ai = new AIService()

  async execute(): Promise<void> {
    const today = getLocalTime().format('YYYY-MM-DD')

    // Run at most once per day across all processes/replicas, so users never get a duplicate
    // briefing toast (and we never double-count usage in llm_usage_log). The manual test
    // trigger calls sendToUser/sendMockToUser directly and is intentionally NOT gated by this.
    const acquired = await acquireRunLock(this.name, today)
    if (!acquired) {
      logger.info({ module: this.name, date: today }, '⏭️ [SendDailyBriefingModule] already ran today — skipping')
      return
    }

    logger.info({ today }, '🌅 [SendDailyBriefingModule] building morning briefings...')

    const snapshot = await db.collection('users').get()
    if (snapshot.empty) {
      logger.warn('ℹ️ [SendDailyBriefingModule] no users found — nothing to send')
      return
    }

    let sent = 0
    for (const doc of snapshot.docs) {
      const userId = doc.id
      try {
        const result = await this.sendToUser(userId, today)
        if (result.sent) sent += 1
      } catch (error) {
        logger.warn({ error, userId }, '[daily-briefing] failed to send for user')
      }
    }

    logger.info({ sent, total: snapshot.size, today }, '✅ [SendDailyBriefingModule] done')
  }

  /**
   * Builds + delivers the briefing toast for a single user (and logs its cost).
   * Returns `{ sent: false }` when the user has nothing today. Also usable on-demand
   * (e.g. a manual test trigger), not only from the daily cron.
   */
  async sendToUser(
    userId: string,
    today: string = getLocalTime().format('YYYY-MM-DD'),
  ): Promise<{ sent: boolean; message?: string }> {
    const briefing = await this.buildBriefing(userId, today)
    if (!briefing) return { sent: false } // nothing today → no toast
    this.emitToast(userId, briefing.text, briefing.quickReply)
    return { sent: true, message: briefing.text }
  }

  /**
   * Emits a briefing built from MOCK counts (no DB read, no cost logging). For manually
   * testing the toast + SSE plumbing regardless of the user's real data.
   */
  async sendMockToUser(
    userId: string,
    scheduleCount = 3,
    todoCount = 5,
  ): Promise<{ sent: boolean; message?: string }> {
    const briefing = await this.composeFromCounts(scheduleCount, todoCount)
    if (!briefing) return { sent: false }
    this.emitToast(userId, briefing.text, briefing.quickReply)
    return { sent: true, message: briefing.text }
  }

  /**
   * Counts today's appointments + pending todos and composes the briefing.
   * Returns null when the user has nothing today (so no toast is sent at all).
   */
  private async buildBriefing(userId: string, today: string): Promise<IBriefing | null> {
    const [schedules, todos] = await Promise.all([
      this.scheduleService.getSchedules(userId, { start_date: today, end_date: today, page: 1, limit: 1 }),
      this.todoService.getTodos(userId, { completed: false, page: 1, limit: 1 }),
    ])
    // Real path: tag the LLM call so its token usage lands in the central ledger.
    return this.composeFromCounts(schedules.metadata.total, todos.metadata.total, {
      source: 'daily-briefing',
      userId,
    })
  }

  /**
   * Composes a briefing (text + quick replies) from the given counts, or null if both are 0.
   * `meta` is forwarded to the LLM call for usage logging; omit it (mock path) to skip logging.
   */
  private async composeFromCounts(
    scheduleCount: number,
    todoCount: number,
    meta?: ILlmUsageMeta,
  ): Promise<IBriefing | null> {
    const parts: string[] = []
    const quickReply: TToastQuickReply = []
    if (scheduleCount > 0) {
      parts.push(`นัดหมาย ${scheduleCount} รายการ`)
      quickReply.push(messageQuickReply('schedule', 'แสดงรายการนัดหมายในวันนี้'))
    }
    if (todoCount > 0) {
      parts.push(`งานที่ต้องทำ ${todoCount} รายการ`)
      quickReply.push(messageQuickReply('todo', 'แสดงรายการที่ต้องทำในวันนี้'))
    }

    if (parts.length === 0) {
      // Nothing today → skip sending entirely.
      return null
    }

    // Join with " และ " before the last item (Thai natural conjunction).
    // Safe to assert non-empty: we returned null above when parts.length === 0.
    const summary =
      parts.length === 1 ? parts[0]! : `${parts.slice(0, -1).join(', ')} และ${parts[parts.length - 1]!}`

    const { text: body } = await this.composeMessage(summary, meta)
    // Always append the CTA deterministically so it never depends on the LLM.
    const text = `${body} — ${PLAN_CTA}`
    return { text, quickReply }
  }

  /**
   * Generates the greeting via the LLM (grounded on the exact `summary`), falling back to
   * a fixed template if the model errors or returns nothing usable. When `meta` is provided
   * (the real cron path, not mock), token usage is recorded in the central `llm_usage_log`
   * ledger by AIService.generate itself.
   */
  private async composeMessage(
    summary: string,
    meta?: ILlmUsageMeta,
  ): Promise<{ text: string; source: 'llm' | 'fallback' }> {
    const fallbackText = `วันนี้คุณมี${summary}` // CTA is appended by the caller

    try {
      const response = await this.ai.generate(
        [{ role: 'user', parts: [{ text: `วันนี้ผู้ใช้มี: ${summary}\nเขียนข้อความทักทายตอนเช้า` }] }],
        { systemInstruction: BRIEFING_INSTRUCTION, temperature: 0.9, meta },
      )
      const raw = response.candidates?.[0]?.content?.parts?.find((p) => p.text)?.text ?? ''
      const text = this.sanitize(raw)
      if (!text) return { text: fallbackText, source: 'fallback' }
      return { text, source: 'llm' }
    } catch (error) {
      logger.warn({ error }, '[daily-briefing] LLM generation failed — using template fallback')
      return { text: fallbackText, source: 'fallback' }
    }
  }

  /** Normalizes model output to a single clean line (strips quotes/newlines/emoji, a stray CTA, caps length). */
  private sanitize(raw: string): string {
    const text = raw
      .trim()
      .replace(/^["'`]+|["'`]+$/g, '')
      .replace(/\s*\n+\s*/g, ' ')
      // Drop any emoji the model added despite instructions.
      .replace(/[\p{Extended_Pictographic}\u{FE0F}\u{200D}]/gu, '')
      // Drop any tap-CTA the model added despite instructions (we append our own).
      .replace(/\s*[—–-]?\s*แตะ(เพื่อ)?วาง.*$/u, '')
      // Collapse any double spaces left by the removals above.
      .replace(/\s{2,}/g, ' ')
      .trim()
    return text.length > 200 ? text.slice(0, 200).trim() : text
  }

  /** Emits the briefing as a transient toast (SSE only — not saved to chat history). */
  private emitToast(userId: string, text: string, quickReply?: TToastQuickReply): void {
    sseBroker.emit(userId, { type: 'toast', message: text, ...(quickReply ? { quick_reply: quickReply } : {}) })
  }
}