import { db } from '#/common/libs/firebase.lib'
import { logger } from '#/common/libs/logger.lib'
import { AIService } from '#/common/services/ai.service'
import { sseBroker } from '#/common/services/sse-broker.service'
import { getLocalTime } from '#/common/utils/datetime.util'
import { ScheduleRepository } from '#/features/schedules/v1/schedule.repository'
import { ScheduleService } from '#/features/schedules/v1/schedule.service'
import { TodoRepository } from '#/features/todos/v1/todo.repository'
import { TodoService } from '#/features/todos/v1/todo.service'
import { envVariables } from '#/factory'

import type { TChatSseEvent } from '#/features/chats/v1/chat.type'
import type { IScheduleModule } from '#/worker/schedule/schedule.type'

type TToastQuickReply = NonNullable<Extract<TChatSseEvent, { type: 'toast' }>['quick_reply']>
type TToastQuickReplyItem = TToastQuickReply[number]

/** Token usage for one briefing generation (0 when the template fallback was used). */
interface IBriefingUsage {
  inputTokens: number
  outputTokens: number
  totalTokens: number
}

interface IBriefing {
  text: string
  quickReply: TToastQuickReply
  scheduleCount: number
  todoCount: number
  source: 'llm' | 'fallback'
  usage: IBriefingUsage
}

/** Collection holding a cost/usage record per briefing — for internal cost evaluation only. */
const NOTIFICATION_LOG_COLLECTION = 'notification_log'

const BRIEFING_INSTRUCTION = `คุณคือผู้ช่วยส่วนตัวที่สรุปภารกิจวันนี้ให้ผู้ใช้เป็นภาษาไทย แบบกระชับ ตรงประเด็น
เขียนสไตล์ "บอกสิ่งที่มีวันนี้ตามตัวเลข" จบในประโยคเดียว

ตัวอย่างโทน (ภาษาอังกฤษ เพื่อให้เห็นสไตล์ ไม่ใช่ให้แปลตรงตัว):
"You have 3 meetings, 5 unread from work, and Sara wants to grab coffee tomorrow."

ให้เขียนเวอร์ชันภาษาไทยในสไตล์เดียวกัน เช่น:
"วันนี้คุณมี 3 นัดหมาย และ 5 สิ่งที่ต้องทำ"

ข้อกำหนดเด็ดขาด:
- ใช้ตัวเลขตามที่กำหนดให้เท่านั้น ห้ามเปลี่ยน ห้ามเพิ่ม ห้ามมั่วจำนวนหรือหมวดที่ไม่ได้ระบุ (เช่น ห้ามแต่ง "อีเมล" หรือ "เพื่อนชวน" ขึ้นมาเองถ้าไม่ได้ให้มา)
- กระชับ ไม่เกิน ~120 ตัวอักษร ขึ้นต้นด้วยสิ่งที่มีวันนี้ได้เลย ไม่ต้องเกริ่นทักทายยาว
- จะปิดท้ายด้วยคำชวนวางแผนสั้น ๆ (เช่น "แตะเพื่อวางแผนวันของคุณ") หรือไม่ใส่ก็ได้
- ตอบกลับเป็น "ข้อความล้วน" บรรทัดเดียว ห้ามใส่เครื่องหมายคำพูด ห้ามขึ้นบรรทัดใหม่ ห้ามใส่ JSON
- ใส่ emoji ได้ไม่เกิน 1 ตัว (ไม่ใส่ก็ได้)`

/** A "message" quick reply: tapping it sends `text` to the agent as a user message. */
function messageQuickReply(label: string, text: string): TToastQuickReplyItem {
  return { type: 'action', action: { type: 'message', label, text } }
}

/**
 * Daily cron: at 08:00 send each user a short "morning briefing" as a transient
 * TOAST (SSE only — NOT persisted to chat history) summarizing what's on their plate
 * today (appointments + pending todos). The wording is generated by an LLM for a natural
 * feel, with a deterministic template fallback. A usage record is logged to
 * `notification_log` for internal cost evaluation (this is a free service — users are
 * NOT charged credits and nothing is written to their chat history).
 */
export class SendDailyBriefingModule implements IScheduleModule {
  readonly name = 'send-daily-briefing'
  readonly cronPattern = '0 8 * * *' // 08:00 daily
  readonly timezone = 'Asia/Bangkok'

  private readonly scheduleService = new ScheduleService(new ScheduleRepository())
  private readonly todoService = new TodoService(new TodoRepository())
  private readonly ai = new AIService()

  async execute(): Promise<void> {
    const today = getLocalTime().format('YYYY-MM-DD')
    logger.info({ today }, '🌅 [SendDailyBriefingModule] building morning briefings...')

    const snapshot = await db.collection('users').get()
    if (snapshot.empty) {
      logger.warn('ℹ️ [SendDailyBriefingModule] no users found — nothing to send')
      return
    }

    let sent = 0
    for (const doc of snapshot.docs) {
      const userId = doc.id
      try {
        const result = await this.sendToUser(userId, today)
        if (result.sent) sent += 1
      } catch (error) {
        logger.warn({ error, userId }, '[daily-briefing] failed to send for user')
      }
    }

    logger.info({ sent, total: snapshot.size, today }, '✅ [SendDailyBriefingModule] done')
  }

  /**
   * Builds + delivers the briefing toast for a single user (and logs its cost).
   * Returns `{ sent: false }` when the user has nothing today. Also usable on-demand
   * (e.g. a manual test trigger), not only from the daily cron.
   */
  async sendToUser(
    userId: string,
    today: string = getLocalTime().format('YYYY-MM-DD'),
  ): Promise<{ sent: boolean; message?: string }> {
    const briefing = await this.buildBriefing(userId, today)
    if (!briefing) return { sent: false } // nothing today → no toast
    this.emitToast(userId, briefing.text, briefing.quickReply)
    await this.logUsage(userId, today, briefing)
    return { sent: true, message: briefing.text }
  }

  /**
   * Emits a briefing built from MOCK counts (no DB read, no cost logging). For manually
   * testing the toast + SSE plumbing regardless of the user's real data.
   */
  async sendMockToUser(
    userId: string,
    scheduleCount = 3,
    todoCount = 5,
  ): Promise<{ sent: boolean; message?: string }> {
    const briefing = await this.composeFromCounts(scheduleCount, todoCount)
    if (!briefing) return { sent: false }
    this.emitToast(userId, briefing.text, briefing.quickReply)
    return { sent: true, message: briefing.text }
  }

  /**
   * Counts today's appointments + pending todos and composes the briefing.
   * Returns null when the user has nothing today (so no toast is sent at all).
   */
  private async buildBriefing(userId: string, today: string): Promise<IBriefing | null> {
    const [schedules, todos] = await Promise.all([
      this.scheduleService.getSchedules(userId, { start_date: today, end_date: today, page: 1, limit: 1 }),
      this.todoService.getTodos(userId, { completed: false, page: 1, limit: 1 }),
    ])
    return this.composeFromCounts(schedules.metadata.total, todos.metadata.total)
  }

  /** Composes a briefing (text + quick replies) from the given counts, or null if both are 0. */
  private async composeFromCounts(scheduleCount: number, todoCount: number): Promise<IBriefing | null> {
    const parts: string[] = []
    const quickReply: TToastQuickReply = []
    if (scheduleCount > 0) {
      parts.push(`นัดหมาย ${scheduleCount} รายการ`)
      quickReply.push(messageQuickReply('schedule', 'แสดงรายการนัดหมายในวันนี้'))
    }
    if (todoCount > 0) {
      parts.push(`งานที่ต้องทำ ${todoCount} รายการ`)
      quickReply.push(messageQuickReply('todo', 'แสดงรายการที่ต้องทำในวันนี้'))
    }

    if (parts.length === 0) {
      // Nothing today → skip sending entirely.
      return null
    }

    // Join with " และ " before the last item (Thai natural conjunction).
    // Safe to assert non-empty: we returned null above when parts.length === 0.
    const summary =
      parts.length === 1 ? parts[0]! : `${parts.slice(0, -1).join(', ')} และ${parts[parts.length - 1]!}`

    const { text, source, usage } = await this.composeMessage(summary)
    return { text, quickReply, scheduleCount, todoCount, source, usage }
  }

  /**
   * Generates the greeting via the LLM (grounded on the exact `summary`), falling back to
   * a fixed template if the model errors or returns nothing usable. Token usage is captured
   * either way for cost accounting.
   */
  private async composeMessage(summary: string): Promise<{ text: string; source: 'llm' | 'fallback'; usage: IBriefingUsage }> {
    const fallbackText = `วันนี้คุณมี${summary} — แตะเพื่อวางแผนวันของคุณ`
    const noUsage: IBriefingUsage = { inputTokens: 0, outputTokens: 0, totalTokens: 0 }

    try {
      const response = await this.ai.generate(
        [{ role: 'user', parts: [{ text: `วันนี้ผู้ใช้มี: ${summary}\nเขียนข้อความทักทายตอนเช้า` }] }],
        { systemInstruction: BRIEFING_INSTRUCTION, temperature: 0.9 },
      )
      const usage: IBriefingUsage = {
        inputTokens: response.usageMetadata?.promptTokenCount ?? 0,
        outputTokens: response.usageMetadata?.candidatesTokenCount ?? 0,
        totalTokens: response.usageMetadata?.totalTokenCount ?? 0,
      }
      const raw = response.candidates?.[0]?.content?.parts?.find((p) => p.text)?.text ?? ''
      const text = this.sanitize(raw)
      // Keep the real usage even when we fall back to the template (tokens were still spent).
      if (!text) return { text: fallbackText, source: 'fallback', usage }
      return { text, source: 'llm', usage }
    } catch (error) {
      logger.warn({ error }, '[daily-briefing] LLM generation failed — using template fallback')
      return { text: fallbackText, source: 'fallback', usage: noUsage }
    }
  }

  /** Normalizes model output to a single clean line (strips quotes/newlines, caps length). */
  private sanitize(raw: string): string {
    const text = raw
      .trim()
      .replace(/^["'`]+|["'`]+$/g, '')
      .replace(/\s*\n+\s*/g, ' ')
      .trim()
    return text.length > 200 ? text.slice(0, 200).trim() : text
  }

  /** Emits the briefing as a transient toast (SSE only — not saved to chat history). */
  private emitToast(userId: string, text: string, quickReply?: TToastQuickReply): void {
    sseBroker.emit(userId, { type: 'toast', message: text, ...(quickReply ? { quick_reply: quickReply } : {}) })
  }

  /** Records a usage row for internal cost evaluation (NOT shown to the user, NOT charged). */
  private async logUsage(userId: string, date: string, briefing: IBriefing): Promise<void> {
    await db.collection(NOTIFICATION_LOG_COLLECTION).add({
      user_id: userId,
      kind: 'daily_briefing',
      date,
      message: briefing.text,
      source: briefing.source,
      model: envVariables.GOOGLE_GEMINI_CHAT_MODEL,
      input_tokens: briefing.usage.inputTokens,
      output_tokens: briefing.usage.outputTokens,
      total_tokens: briefing.usage.totalTokens,
      schedule_count: briefing.scheduleCount,
      todo_count: briefing.todoCount,
      created_at: new Date(),
    })
  }
}