import { z } from 'zod'

import { paginationFilterSchema } from '#/common/schemas/request.schema'
import { paginationMetadataSchema } from '#/common/schemas/response.schema'

// Request body for POST /images/codes. `limit` caps how many image-insights
// requests the code allows; -1 means unlimited.
export const imageCodeCreatePayloadSchema = z.object({
  limit: z.number().int().min(-1).default(-1),
})

// Generated by POST /images/codes — handed out to whoever should get access.
export const imageCodeResponseSchema = z.object({
  code: z.string(),
  limit: z.number(),
})

// GET /images/codes — admin listing.
export const imageCodeFilterPayloadSchema = paginationFilterSchema

export const imageCodeListItemSchema = z.object({
  uuid: z.string(),
  code: z.string(),
  // Usage quota: how many insights requests are allowed (-1 = unlimited) vs made.
  limit: z.number(),
  count: z.number(),
  disabled: z.boolean(),
  // Aggregated LLM token usage across all insights requests for this code.
  usage: z.object({
    input_tokens: z.number(),
    output_tokens: z.number(),
    total_tokens: z.number(),
  }),
  created_by: z.string(),
  created_at: z.string(),
})

export const imageCodeListResponseSchema = z.object({
  items: z.array(imageCodeListItemSchema),
  metadata: paginationMetadataSchema,
})

// Exchanged at POST /images/invites for an access token.
export const imageInviteCreatePayloadSchema = z.object({
  code: z.string().min(1),
})

export const imageInviteResponseSchema = z.object({
  token: z.string(),
})
