import type {
  imageCodeCreatePayloadSchema,
  imageCodeFilterPayloadSchema,
  imageCodeListItemSchema,
  imageCodeListResponseSchema,
  imageCodeResponseSchema,
  imageInviteCreatePayloadSchema,
  imageInviteResponseSchema,
} from '#/features/image-invites/v1/image-invite.schema'
import type { z } from 'zod'

export type TImageCodeCreatePayload = z.infer<typeof imageCodeCreatePayloadSchema>
export type TImageCodeResponse = z.infer<typeof imageCodeResponseSchema>
export type TImageCodeFilterPayload = z.infer<typeof imageCodeFilterPayloadSchema>
export type TImageCodeListItem = z.infer<typeof imageCodeListItemSchema>
export type TImageCodeListResponse = z.infer<typeof imageCodeListResponseSchema>
export type TImageInviteCreatePayload = z.infer<typeof imageInviteCreatePayloadSchema>
export type TImageInviteResponse = z.infer<typeof imageInviteResponseSchema>

/** An invite code generated by an admin and handed out to a recipient. */
export interface IImageCodeEntity {
  uuid: string
  code: string
  /** Max number of image-insights requests allowed. -1 = unlimited. */
  limit: number
  /** Number of image-insights requests made so far against this code. */
  count: number
  /** When true the code is blocked — exchange and insights both return 403. */
  disabled: boolean
  created_by: string
  created_at: string
}

/** An access token issued when a valid code is exchanged. Used as `x-api-key`. */
export interface IImageInviteEntity {
  uuid: string
  token: string
  code: string
  code_uuid: string
  created_at: string
}

/** Per-request LLM token usage recorded for an image-insights call. */
export interface IImageInsightUsageEntity {
  uuid: string
  code: string
  code_uuid: string
  invite_uuid: string
  model: string
  input_tokens: number
  output_tokens: number
  total_tokens: number
  created_at: string
}

/** Aggregated token usage totals for a single code. */
export interface IUsageTotals {
  input_tokens: number
  output_tokens: number
  total_tokens: number
}

/** Outcome of atomically consuming one unit of a code's usage quota. */
export interface TConsumeCodeResult {
  ok: boolean
  /** Why consumption failed (absent when ok). */
  reason?: 'not_found' | 'disabled' | 'limit'
  count: number
  limit: number
}
