export enum ERouteTag {
  HEALTH = 'Health',
  USER = 'User',
  SCHEDULE = 'Schedule',
  TODO = 'Todo',
  EXPENSE = 'Expense',
  ACCOUNT = 'Account',
  MOOD = 'Mood',
  CHAT = 'Chat',
  UID = 'Uid',
  SUMMARY = 'Summary',
  PARSER = 'Parser',
  HOROSCOPE = 'Horoscope',
  IMAGE_INSIGHT = 'Image Insight',
}
